FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /hist_ingestion

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

COPY services/hist_ingestion/src ./src/

CMD ["uv", "run", "src/generate_preprocessor.py"]