# Redis Configuration for MLOps Online Store
# ==========================================

# Persistence disabled (Real-time only)
save ""
appendonly no

# Memory Management (Protect host from OOM)
maxmemory 512mb
maxmemory-policy allkeys-lru

# Networking
port 6379
bind 0.0.0.0
