"""
Data Sources for Feast Feature Store

This module defines both batch (offline) and streaming data sources
for the washing machine anomaly detection system.
"""

from feast import FileSource, PushSource

# ============================================================================
# BATCH DATA SOURCE (Historical Data)
# ============================================================================
# Points to Parquet files generated by historical ingestion service
# These files contain historical features for training and batch scoring
batch_source = FileSource(
    name='washing_batch_source',
    path='/app/data/processed_datasets/industrial_washer_normal_features/',
    timestamp_field='timestamp',
    description='Batch source for historical washing machine features'
)

# ============================================================================
# STREAMING DATA SOURCE (Real-time Data)
# ============================================================================
# PushSource allows real-time feature ingestion
# Features pushed here are materialized to Redis for low-latency serving
stream_source = PushSource(
    name='washing_stream_source',
    batch_source=batch_source,  # Links to batch source for historical context
    description='Push source for real-time washing machine features'
)